### ISSUE TITLE
AttributeError: 'module' object has no attribute 'total_variation'

### ISSUE THREAD

**Issue by gregpaulos** [cysmith/neural-style-tf#38]
Attempting to run on floydhub. Uploaded the vgg weights as a dataset file on floydhub. 

Using the floyd-cli, ran in my terminal:
floyd run --gpu --env tensorflow-0.12:py2 --data datasets/vggforstyle/1:vgg "python neural_style.py --content_img golden_gate.jpg --style_imgs starry-night.jpg --original_colors --model_weights /vgg/imagenet-vgg-verydeep-19.mat --img_output_dir /output --verbose;"

And get the following error in the log:
2017-09-13 13:56:16,853 INFO - Traceback (most recent call last):
2017-09-13 13:56:16,855 INFO - File "neural_style.py", line 856, in <module>
2017-09-13 13:56:16,856 INFO - main()
2017-09-13 13:56:16,856 INFO - File "neural_style.py", line 853, in main
2017-09-13 13:56:16,856 INFO - else: render_single_image()
2017-09-13 13:56:16,856 INFO - File "neural_style.py", line 822, in render_single_image
2017-09-13 13:56:16,856 INFO - stylize(content_img, style_imgs, init_img)
2017-09-13 13:56:16,856 INFO - File "neural_style.py", line 562, in stylize
2017-09-13 13:56:16,856 INFO - L_tv = tf.image.total_variation(net['input'])
2017-09-13 13:56:16,857 INFO - AttributeError: 'module' object has no attribute 'total_variation'

Any suggestions?

Thanks!

**Comment by cysmith** [comment]
Update your TensorFlow to the most recent version.

**Comment by gregpaulos** [comment]
Awesome - totally worked - thanks for the lightning-quick response!

(And duh on me for the rookie mistake)

**Comment by lcb931023** [comment]
The readme's "Implementation Details" section still lists this project as tested with tensorflow (0.10.0rc). Let's update it so that more people will have an easier time setting it up :)

**Comment by Leif-US** [comment]
Seems to be working with 1.0.0. Newer versions don't work because of incompatibility with Python 2
